# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-03 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseDatos', '0001_initial'),
        ('palabraClave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(error_messages={'required': 'Por favor, ingrese un titulo'}, max_length=200)),
                ('ISBN', models.CharField(blank=True, max_length=100, null=True)),
                ('Anio', models.CharField(blank=True, max_length=20, null=True)),
                ('Editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('Resumen', models.TextField(null=True)),
                ('Documento', models.FileField(blank=True, null=True, upload_to='libro/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('Url', models.URLField(blank=True, null=True)),
                ('Doi', models.URLField(blank=True, max_length=100, null=True)),
                ('UbicacionFisica', models.CharField(blank=True, max_length=200, null=True)),
                ('capitulo', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('capitulo', 'Capitulo de libro'), ('libro', 'Libro completo')], max_length=200, null=True)),
                ('autoresLibro', models.CharField(blank=True, max_length=400, null=True)),
                ('BaseDatos', models.ManyToManyField(blank=True, to='baseDatos.baseDatos')),
                ('PalabrasClave', models.ManyToManyField(blank=True, to='palabraClave.palabraClave')),
            ],
            options={
                'permissions': (('ver_libro', 'ver libro'),),
            },
        ),
    ]
