# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-10 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0001_initial'),
        ('informacionLaboral', '0002_auto_20180603_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionlaboral',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universidad.universidad'),
        ),
    ]
