# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-08 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
        ('Formacion_Academica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacion_academica',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pais.pais'),
        ),
        migrations.AlterField(
            model_name='formacion_academica',
            name='nombreCentroEstudios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universidad.universidad'),
        ),
    ]
