# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-11 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universidad',
            name='instituto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='Nombre',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='Rector',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
