# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-03 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autoresArticulos', '0001_initial'),
        ('Linea_Investigacion', '0001_initial'),
        ('Sub_Lin_Investigacion', '0001_initial'),
        ('palabraClave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('financiamiento', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('montoFinanciado', models.CharField(max_length=200)),
                ('montorecibido', models.CharField(max_length=200)),
                ('fechaInicial', models.DateField()),
                ('fechaFinal', models.DateField()),
                ('estado', models.CharField(choices=[('En espera de Presupuesto', 'En espera de Presupuesto'), ('En Ejecución', 'En Ejecución'), ('Finalizado', 'Finalizado')], max_length=200)),
                ('resumen', models.TextField()),
                ('tipoProyecto', models.CharField(choices=[('Formativo', 'Formativo'), ('Generativo', 'Generativo')], max_length=255)),
                ('documentos', models.FileField(blank=True, null=True, upload_to='proyecto/')),
                ('integrantes', models.ManyToManyField(blank=True, to='autoresArticulos.autoresArticulos')),
                ('lineaInvestigacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Linea_Investigacion.linea_investigacion')),
                ('palabrasClaves', models.ManyToManyField(blank=True, to='palabraClave.palabraClave')),
                ('subLinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sub_Lin_Investigacion.sub_lin_investigacion')),
            ],
            options={
                'permissions': (('ver_Proyectos', 'ver Proyectos'),),
            },
        ),
    ]
