# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='integrantes',
        ),
    ]
