# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-11 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrera', '0001_initial'),
        ('Sub_Lin_Investigacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_lin_investigacion',
            name='Carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrera.carrera'),
        ),
    ]
