# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-04 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ponencia', '0002_auto_20180604_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponencia',
            name='financia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
