# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-06 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoresLibro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreslibro',
            name='capituloTitulo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='autoreslibro',
            name='gradoAutoria',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
