# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-11 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoresLibro', '0003_autoreslibro_capitulosel'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreslibro',
            name='capituloNumero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
